name: juicer_gen_test
version: 0.10.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  juicer: # ^0.10.0
    path: ../juicer

dev_dependencies:
  test:
  build_test: any
  build_runner: any
  build_web_compilers: any

