import "package:juicer/metadata.dart";
import "something.dart";

/// This is a different class. Different to `Something`.
@juiced
class Different {
  Different(this.fooString);

  Different.json();

  String fooString;
  Something something;

  Map<String, /*List<int>*/ dynamic> deep; // deep types are not supported yet

  Map<String, Map> notSoDeep;

  Map<String, Different> otherNamedDiffs;

  /// It's a random number generated by a fair die roll at the time of writing.
  /// Yeah, no, it's not.
  /// But it might as well be.
  int get readOnly => 7;

  set writeOnly(String value) => print(value);
}
